#!/bin/sh

#function cdexec() {
#	cd "$( dirname "$( realpath "$@" )" )"
#	basename "$@"
#}

function touchx() {
	touch "$@"
	chmod +x "$@"
}

function ccr() {
	gcc "$@" && ./a.out
}
function cxxr() {
	g++ "$@" && ./a.out
}

function gitacp() {
	git add . && git commit -m "$1" && git push
}
function gitacpc() {
	git add . && git commit && git push
}
